/* Generated by Yosys 0.43+3 (git sha1 b08688f71, clang++ 14.0.0-1ubuntu1.1 -fPIC -Os) */

(* top =  1  *)
(* src = "./riscv_csr_regfile.v:41.1-643.10" *)
module riscv_csr_regfile(clk_i, rst_i, ext_intr_i, timer_intr_i, cpu_id_i, misa_i, exception_i, exception_pc_i, exception_addr_i, csr_ren_i, csr_raddr_i, csr_rdata_o, csr_waddr_i, csr_wdata_i, csr_branch_o, csr_target_o, priv_o, status_o, satp_o, interrupt_o);
  (* src = "./riscv_csr_regfile.v:585.1-630.4" *)
  wire _000_;
  (* src = "./riscv_csr_regfile.v:585.1-630.4" *)
  wire [31:0] _001_;
  (* src = "./riscv_csr_regfile.v:497.1-577.4" *)
  wire [31:0] _002_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _003_;
  (* src = "./riscv_csr_regfile.v:497.1-577.4" *)
  wire [31:0] _004_;
  (* src = "./riscv_csr_regfile.v:497.1-577.4" *)
  wire [31:0] _005_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _006_;
  (* src = "./riscv_csr_regfile.v:497.1-577.4" *)
  wire [31:0] _007_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _008_;
  (* src = "./riscv_csr_regfile.v:497.1-577.4" *)
  wire [31:0] _009_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _010_;
  (* src = "./riscv_csr_regfile.v:497.1-577.4" *)
  wire [31:0] _011_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _012_;
  (* src = "./riscv_csr_regfile.v:497.1-577.4" *)
  wire [31:0] _013_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _014_;
  (* src = "./riscv_csr_regfile.v:164.1-170.27" *)
  wire _015_;
  (* src = "./riscv_csr_regfile.v:497.1-577.4" *)
  wire [31:0] _016_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _017_;
  (* src = "./riscv_csr_regfile.v:497.1-577.4" *)
  wire _018_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire _019_;
  (* src = "./riscv_csr_regfile.v:497.1-577.4" *)
  wire [31:0] _020_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _021_;
  (* src = "./riscv_csr_regfile.v:497.1-577.4" *)
  wire [31:0] _022_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _023_;
  (* src = "./riscv_csr_regfile.v:497.1-577.4" *)
  wire [31:0] _024_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _025_;
  (* src = "./riscv_csr_regfile.v:497.1-577.4" *)
  wire [31:0] _026_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _027_;
  (* src = "./riscv_csr_regfile.v:132.1-150.4" *)
  wire [31:0] _028_;
  (* src = "./riscv_csr_regfile.v:132.1-150.4" *)
  wire [31:0] _029_;
  (* src = "./riscv_csr_regfile.v:153.1-157.30" *)
  wire [1:0] _030_;
  (* src = "./riscv_csr_regfile.v:178.1-213.4" *)
  wire [31:0] _031_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire _032_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [1:0] _033_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [1:0] _034_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _035_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _036_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _037_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _038_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire _039_;
  (* src = "./riscv_csr_regfile.v:585.1-630.4" *)
  wire _040_;
  (* src = "./riscv_csr_regfile.v:585.1-630.4" *)
  wire [31:0] _041_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _042_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _043_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _044_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _045_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _046_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire _047_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _048_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _049_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _050_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire _051_;
  (* src = "./riscv_csr_regfile.v:585.1-630.4" *)
  wire _052_;
  (* src = "./riscv_csr_regfile.v:585.1-630.4" *)
  wire [31:0] _053_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _054_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _055_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _056_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire _057_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _058_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _059_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire _060_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _061_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _062_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _063_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire _064_;
  (* src = "./riscv_csr_regfile.v:585.1-630.4" *)
  wire _065_;
  (* src = "./riscv_csr_regfile.v:585.1-630.4" *)
  wire [31:0] _066_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _067_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _068_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _069_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire _070_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _071_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _072_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire _073_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _074_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _075_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _076_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire _077_;
  (* src = "./riscv_csr_regfile.v:585.1-630.4" *)
  wire _078_;
  (* src = "./riscv_csr_regfile.v:585.1-630.4" *)
  wire [31:0] _079_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _080_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _081_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _082_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _083_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _084_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire _085_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _086_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _087_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _088_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [1:0] _089_;
  (* src = "./riscv_csr_regfile.v:585.1-630.4" *)
  wire _090_;
  (* src = "./riscv_csr_regfile.v:585.1-630.4" *)
  wire [31:0] _091_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _092_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _093_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _094_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [1:0] _095_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _096_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire _097_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _098_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _099_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _100_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire _101_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire _102_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire [31:0] _103_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  wire _104_;
  (* src = "./riscv_csr_regfile.v:557.27-557.49" *)
  wire [31:0] _105_;
  (* src = "./riscv_csr_regfile.v:628.27-628.49" *)
  wire [31:0] _106_;
  (* src = "./riscv_csr_regfile.v:167.24-167.46" *)
  wire _107_;
  (* src = "./riscv_csr_regfile.v:167.65-167.87" *)
  wire _108_;
  (* src = "./riscv_csr_regfile.v:169.10-169.32" *)
  wire _109_;
  (* src = "./riscv_csr_regfile.v:169.36-169.58" *)
  wire _110_;
  (* src = "./riscv_csr_regfile.v:172.35-172.57" *)
  wire _111_;
  (* src = "./riscv_csr_regfile.v:172.75-172.97" *)
  wire _112_;
  (* src = "./riscv_csr_regfile.v:281.9-281.39" *)
  wire _113_;
  (* src = "./riscv_csr_regfile.v:284.13-284.31" *)
  wire _114_;
  (* src = "./riscv_csr_regfile.v:313.29-313.48" *)
  wire _115_;
  (* src = "./riscv_csr_regfile.v:338.13-338.37" *)
  wire _116_;
  (* src = "./riscv_csr_regfile.v:475.29-475.59" *)
  wire _117_;
  (* src = "./riscv_csr_regfile.v:556.9-556.37" *)
  wire _118_;
  (* src = "./riscv_csr_regfile.v:591.9-591.29" *)
  wire _119_;
  (* src = "./riscv_csr_regfile.v:594.28-594.46" *)
  wire _120_;
  (* src = "./riscv_csr_regfile.v:600.13-600.37" *)
  wire _121_;
  (* src = "./riscv_csr_regfile.v:625.14-625.34" *)
  wire _122_;
  (* src = "./riscv_csr_regfile.v:335.14-335.34" *)
  wire _123_;
  (* src = "./riscv_csr_regfile.v:597.14-597.34" *)
  wire _124_;
  (* src = "./riscv_csr_regfile.v:335.38-335.58" *)
  wire _125_;
  (* src = "./riscv_csr_regfile.v:597.38-597.58" *)
  wire _126_;
  (* src = "./riscv_csr_regfile.v:167.52-167.87" *)
  wire _127_;
  (* src = "./riscv_csr_regfile.v:167.11-167.46" *)
  wire _128_;
  (* src = "./riscv_csr_regfile.v:172.22-172.57" *)
  wire _129_;
  (* src = "./riscv_csr_regfile.v:172.62-172.97" *)
  wire _130_;
  (* src = "./riscv_csr_regfile.v:335.14-335.58" *)
  wire _131_;
  (* src = "./riscv_csr_regfile.v:469.9-469.43" *)
  wire _132_;
  (* src = "./riscv_csr_regfile.v:470.9-470.43" *)
  wire _133_;
  (* src = "./riscv_csr_regfile.v:471.9-471.42" *)
  wire _134_;
  (* src = "./riscv_csr_regfile.v:472.9-472.42" *)
  wire _135_;
  (* src = "./riscv_csr_regfile.v:475.9-475.59" *)
  wire _136_;
  (* src = "./riscv_csr_regfile.v:597.14-597.58" *)
  wire _137_;
  (* src = "./riscv_csr_regfile.v:167.10-167.88" *)
  wire _138_;
  (* src = "./riscv_csr_regfile.v:169.10-169.58" *)
  wire _139_;
  (* src = "./riscv_csr_regfile.v:169.10-169.76" *)
  wire _140_;
  (* src = "./riscv_csr_regfile.v:470.25-470.43" *)
  wire _141_;
  (* src = "./riscv_csr_regfile.v:472.25-472.42" *)
  wire _142_;
  (* src = "./riscv_csr_regfile.v:172.21-172.98" *)
  wire _143_;
  (* src = "./riscv_csr_regfile.v:459.36-459.201" *)
  wire [31:0] _144_;
  (* src = "./riscv_csr_regfile.v:460.40-460.138" *)
  wire [31:0] _145_;
  (* src = "./riscv_csr_regfile.v:461.40-461.138" *)
  wire [31:0] _146_;
  wire [31:0] _147_;
  wire [31:0] _148_;
  wire [31:0] _149_;
  wire [31:0] _150_;
  wire [31:0] _151_;
  wire [31:0] _152_;
  wire [31:0] _153_;
  wire [6:0] _154_;
  wire _155_;
  wire [2:0] _156_;
  wire _157_;
  wire [31:0] _158_;
  wire [31:0] _159_;
  wire [22:0] _160_;
  wire [1:0] _161_;
  wire [2:0] _162_;
  wire _163_;
  wire [31:0] _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire [31:0] _171_;
  wire [31:0] _172_;
  wire [31:0] _173_;
  wire [31:0] _174_;
  wire _175_;
  wire [31:0] _176_;
  wire [31:0] _177_;
  wire [31:0] _178_;
  wire [31:0] _179_;
  wire [18:0] _180_;
  wire [31:0] _181_;
  wire [1:0] _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire [31:0] _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire [1:0] _198_;
  wire [1:0] _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire [31:0] _205_;
  wire _206_;
  wire [31:0] _207_;
  wire [31:0] _208_;
  wire [31:0] _209_;
  wire [31:0] _210_;
  wire [1:0] _211_;
  wire [1:0] _212_;
  wire [31:0] _213_;
  wire [31:0] _214_;
  wire [31:0] _215_;
  wire [31:0] _216_;
  wire [31:0] _217_;
  wire [31:0] _218_;
  wire [31:0] _219_;
  wire [31:0] _220_;
  wire [31:0] _221_;
  wire [31:0] _222_;
  wire [31:0] _223_;
  wire [31:0] _224_;
  wire [31:0] _225_;
  wire [31:0] _226_;
  wire [31:0] _227_;
  wire [31:0] _228_;
  wire _229_;
  wire [1:0] _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire [31:0] _236_;
  wire [31:0] _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire [1:0] _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire [1:0] _254_;
  wire _255_;
  wire _256_;
  wire [31:0] _257_;
  wire _258_;
  wire [31:0] _259_;
  wire _260_;
  wire _261_;
  wire [31:0] _262_;
  wire _263_;
  wire [31:0] _264_;
  wire [31:0] _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire [31:0] _270_;
  wire _271_;
  wire [31:0] _272_;
  wire [31:0] _273_;
  wire [31:0] _274_;
  wire _275_;
  wire _276_;
  wire [31:0] _277_;
  wire [31:0] _278_;
  wire [31:0] _279_;
  wire _280_;
  wire _281_;
  wire [31:0] _282_;
  wire [31:0] _283_;
  wire [31:0] _284_;
  wire _285_;
  wire [31:0] _286_;
  wire [31:0] _287_;
  wire [31:0] _288_;
  wire _289_;
  wire _290_;
  wire [31:0] _291_;
  wire [31:0] _292_;
  wire [31:0] _293_;
  wire _294_;
  wire [31:0] _295_;
  wire [31:0] _296_;
  wire [31:0] _297_;
  wire _298_;
  wire [31:0] _299_;
  wire [31:0] _300_;
  wire [31:0] _301_;
  wire _302_;
  wire [31:0] _303_;
  wire [31:0] _304_;
  wire [18:0] _305_;
  wire [18:0] _306_;
  wire [2:0] _307_;
  wire [2:0] _308_;
  wire [2:0] _309_;
  wire [2:0] _310_;
  wire [2:0] _311_;
  wire [2:0] _312_;
  wire [31:0] _313_;
  wire [31:0] _314_;
  wire [31:0] _315_;
  wire [31:0] _316_;
  wire [31:0] _317_;
  wire [31:0] _318_;
  wire _319_;
  wire _320_;
  wire [1:0] _321_;
  wire [1:0] _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire [31:0] _327_;
  wire [31:0] _328_;
  wire [31:0] _329_;
  wire [31:0] _330_;
  wire [31:0] _331_;
  wire [31:0] _332_;
  (* src = "./riscv_csr_regfile.v:169.63-169.75" *)
  wire _333_;
  (* src = "./riscv_csr_regfile.v:553.27-553.64" *)
  wire [31:0] _334_;
  (* src = "./riscv_csr_regfile.v:594.27-594.75" *)
  wire [31:0] _335_;
  (* src = "./riscv_csr_regfile.v:582.12-582.20" *)
  reg branch_r;
  (* src = "./riscv_csr_regfile.v:583.12-583.27" *)
  reg [31:0] branch_target_r;
  (* src = "./riscv_csr_regfile.v:172.6-172.18" *)
  wire buffer_mip_w;
  (* src = "./riscv_csr_regfile.v:53.22-53.27" *)
  input clk_i;
  wire clk_i;
  (* src = "./riscv_csr_regfile.v:59.22-59.30" *)
  input [31:0] cpu_id_i;
  wire [31:0] cpu_id_i;
  (* src = "./riscv_csr_regfile.v:75.22-75.34" *)
  output csr_branch_o;
  wire csr_branch_o;
  (* src = "./riscv_csr_regfile.v:97.13-97.25" *)
  reg [31:0] csr_mcause_q;
  (* src = "./riscv_csr_regfile.v:225.13-225.25" *)
  reg [31:0] csr_mcause_r;
  (* src = "./riscv_csr_regfile.v:104.13-104.27" *)
  reg [31:0] csr_mcycle_h_q;
  (* src = "./riscv_csr_regfile.v:103.13-103.25" *)
  reg [31:0] csr_mcycle_q;
  (* src = "./riscv_csr_regfile.v:232.13-232.25" *)
  reg [31:0] csr_mcycle_r;
  (* src = "./riscv_csr_regfile.v:96.13-96.23" *)
  reg [31:0] csr_mepc_q;
  (* src = "./riscv_csr_regfile.v:224.13-224.23" *)
  reg [31:0] csr_mepc_r;
  (* src = "./riscv_csr_regfile.v:110.13-110.26" *)
  (* unused_bits = "0 1 2 3 4 5 6 8 9 10 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  reg [31:0] csr_mideleg_q;
  (* src = "./riscv_csr_regfile.v:101.13-101.22" *)
  reg [31:0] csr_mie_q;
  (* src = "./riscv_csr_regfile.v:230.13-230.22" *)
  reg [31:0] csr_mie_r;
  (* src = "./riscv_csr_regfile.v:239.13-239.27" *)
  reg [31:0] csr_mip_next_q;
  (* src = "./riscv_csr_regfile.v:240.13-240.27" *)
  reg [31:0] csr_mip_next_r;
  (* src = "./riscv_csr_regfile.v:100.13-100.22" *)
  reg [31:0] csr_mip_q;
  (* src = "./riscv_csr_regfile.v:229.13-229.22" *)
  reg [31:0] csr_mip_r;
  (* src = "./riscv_csr_regfile.v:162.5-162.18" *)
  reg csr_mip_upd_q;
  (* src = "./riscv_csr_regfile.v:102.13-102.24" *)
  reg [1:0] csr_mpriv_q;
  (* src = "./riscv_csr_regfile.v:105.13-105.27" *)
  reg [31:0] csr_mscratch_q;
  (* src = "./riscv_csr_regfile.v:233.13-233.27" *)
  reg [31:0] csr_mscratch_r;
  (* src = "./riscv_csr_regfile.v:108.13-108.27" *)
  reg csr_mtime_ie_q;
  (* src = "./riscv_csr_regfile.v:235.13-235.27" *)
  reg csr_mtime_ie_r;
  (* src = "./riscv_csr_regfile.v:107.13-107.27" *)
  reg [31:0] csr_mtimecmp_q;
  (* src = "./riscv_csr_regfile.v:234.13-234.27" *)
  reg [31:0] csr_mtimecmp_r;
  (* src = "./riscv_csr_regfile.v:106.13-106.24" *)
  reg [31:0] csr_mtval_q;
  (* src = "./riscv_csr_regfile.v:226.13-226.24" *)
  reg [31:0] csr_mtval_r;
  (* src = "./riscv_csr_regfile.v:99.13-99.24" *)
  reg [31:0] csr_mtvec_q;
  (* src = "./riscv_csr_regfile.v:228.13-228.24" *)
  reg [31:0] csr_mtvec_r;
  (* src = "./riscv_csr_regfile.v:68.22-68.33" *)
  input [11:0] csr_raddr_i;
  wire [11:0] csr_raddr_i;
  (* src = "./riscv_csr_regfile.v:69.22-69.33" *)
  output [31:0] csr_rdata_o;
  wire [31:0] csr_rdata_o;
  (* src = "./riscv_csr_regfile.v:67.22-67.31" *)
  input csr_ren_i;
  wire csr_ren_i;
  (* src = "./riscv_csr_regfile.v:117.13-117.23" *)
  reg [31:0] csr_satp_q;
  (* src = "./riscv_csr_regfile.v:113.13-113.23" *)
  reg [31:0] csr_sepc_q;
  (* src = "./riscv_csr_regfile.v:98.13-98.21" *)
  reg [31:0] csr_sr_q;
  (* src = "./riscv_csr_regfile.v:227.13-227.21" *)
  reg [31:0] csr_sr_r;
  (* src = "./riscv_csr_regfile.v:114.13-114.24" *)
  reg [31:0] csr_stvec_q;
  (* src = "./riscv_csr_regfile.v:76.22-76.34" *)
  output [31:0] csr_target_o;
  wire [31:0] csr_target_o;
  (* src = "./riscv_csr_regfile.v:72.22-72.33" *)
  input [11:0] csr_waddr_i;
  wire [11:0] csr_waddr_i;
  (* src = "./riscv_csr_regfile.v:73.22-73.33" *)
  input [31:0] csr_wdata_i;
  wire [31:0] csr_wdata_i;
  (* src = "./riscv_csr_regfile.v:64.22-64.38" *)
  input [31:0] exception_addr_i;
  wire [31:0] exception_addr_i;
  (* src = "./riscv_csr_regfile.v:62.22-62.33" *)
  input [5:0] exception_i;
  wire [5:0] exception_i;
  (* src = "./riscv_csr_regfile.v:63.22-63.36" *)
  input [31:0] exception_pc_i;
  wire [31:0] exception_pc_i;
  (* src = "./riscv_csr_regfile.v:251.6-251.19" *)
  wire exception_s_w;
  (* src = "./riscv_csr_regfile.v:56.22-56.32" *)
  input ext_intr_i;
  wire ext_intr_i;
  (* src = "./riscv_csr_regfile.v:84.22-84.33" *)
  output [31:0] interrupt_o;
  wire [31:0] interrupt_o;
  (* src = "./riscv_csr_regfile.v:124.12-124.24" *)
  reg [31:0] irq_masked_r;
  (* src = "./riscv_csr_regfile.v:152.11-152.21" *)
  reg [1:0] irq_priv_q;
  (* src = "./riscv_csr_regfile.v:125.12-125.22" *)
  reg [1:0] irq_priv_r;
  (* src = "./riscv_csr_regfile.v:250.6-250.20" *)
  wire is_exception_w;
  (* src = "./riscv_csr_regfile.v:60.22-60.28" *)
  input [31:0] misa_i;
  wire [31:0] misa_i;
  (* src = "./riscv_csr_regfile.v:79.22-79.28" *)
  output [1:0] priv_o;
  wire [1:0] priv_o;
  (* src = "./riscv_csr_regfile.v:177.12-177.19" *)
  reg [31:0] rdata_r;
  (* src = "./riscv_csr_regfile.v:54.22-54.27" *)
  input rst_i;
  wire rst_i;
  (* src = "./riscv_csr_regfile.v:81.22-81.28" *)
  output [31:0] satp_o;
  wire [31:0] satp_o;
  (* src = "./riscv_csr_regfile.v:80.22-80.30" *)
  output [31:0] status_o;
  wire [31:0] status_o;
  (* src = "./riscv_csr_regfile.v:57.22-57.34" *)
  input timer_intr_i;
  wire timer_intr_i;
  assign _006_ = csr_mcycle_q + (* src = "./riscv_csr_regfile.v:266.23-266.43" *) 32'd1;
  assign _105_ = csr_mcycle_h_q + (* src = "./riscv_csr_regfile.v:557.27-557.49" *) 32'd1;
  assign _106_ = exception_pc_i + (* src = "./riscv_csr_regfile.v:628.27-628.49" *) 32'd4;
  assign _029_ = csr_mip_q & (* src = "./riscv_csr_regfile.v:146.28-146.49" *) csr_mie_q;
  assign _107_ = csr_raddr_i == (* src = "./riscv_csr_regfile.v:167.24-167.46" *) 12'h344;
  assign _108_ = csr_raddr_i == (* src = "./riscv_csr_regfile.v:167.65-167.87" *) 12'h144;
  assign _109_ = csr_waddr_i == (* src = "./riscv_csr_regfile.v:169.10-169.32" *) 12'h344;
  assign _110_ = csr_waddr_i == (* src = "./riscv_csr_regfile.v:169.36-169.58" *) 12'h144;
  assign _111_ = csr_raddr_i == (* src = "./riscv_csr_regfile.v:172.35-172.57" *) 12'h344;
  assign _112_ = csr_raddr_i == (* src = "./riscv_csr_regfile.v:172.75-172.97" *) 12'h144;
  assign is_exception_w = { exception_i[5:4], 4'h0 } == (* src = "./riscv_csr_regfile.v:250.24-250.54" *) 6'h10;
  assign _113_ = { exception_i[5:4], 4'h0 } == (* src = "./riscv_csr_regfile.v:281.9-281.39" *) 6'h20;
  assign _114_ = irq_priv_q == (* src = "./riscv_csr_regfile.v:284.13-284.31" *) 2'h3;
  assign _115_ = csr_mpriv_q == (* src = "./riscv_csr_regfile.v:313.29-313.48" *) 2'h1;
  assign _116_ = exception_i[1:0] == (* src = "./riscv_csr_regfile.v:338.13-338.37" *) 2'h3;
  assign _117_ = csr_mcycle_q == (* src = "./riscv_csr_regfile.v:475.29-475.59" *) csr_mtimecmp_q;
  assign _118_ = csr_mcycle_q == (* src = "./riscv_csr_regfile.v:556.9-556.37" *) 32'd4294967295;
  assign _119_ = exception_i == (* src = "./riscv_csr_regfile.v:591.9-591.29" *) 6'h20;
  assign _120_ = irq_priv_q == (* src = "./riscv_csr_regfile.v:594.28-594.46" *) 2'h3;
  assign _121_ = exception_i[1:0] == (* src = "./riscv_csr_regfile.v:600.13-600.37" *) 2'h3;
  assign _122_ = exception_i == (* src = "./riscv_csr_regfile.v:625.14-625.34" *) 6'h34;
  assign _123_ = exception_i >= (* src = "./riscv_csr_regfile.v:335.14-335.34" *) 6'h30;
  assign _124_ = exception_i >= (* src = "./riscv_csr_regfile.v:597.14-597.34" *) 6'h30;
  assign _125_ = exception_i <= (* src = "./riscv_csr_regfile.v:335.38-335.58" *) 6'h33;
  assign _126_ = exception_i <= (* src = "./riscv_csr_regfile.v:597.38-597.58" *) 6'h33;
  assign _127_ = csr_ren_i && (* src = "./riscv_csr_regfile.v:167.52-167.87" *) _108_;
  assign _128_ = csr_ren_i && (* src = "./riscv_csr_regfile.v:167.11-167.46" *) _107_;
  assign _129_ = csr_ren_i && (* src = "./riscv_csr_regfile.v:172.22-172.57" *) _111_;
  assign _130_ = csr_ren_i && (* src = "./riscv_csr_regfile.v:172.62-172.97" *) _112_;
  assign _131_ = _123_ && (* src = "./riscv_csr_regfile.v:335.14-335.58" *) _125_;
  assign _132_ = ext_intr_i && (* src = "./riscv_csr_regfile.v:469.9-469.43" *) csr_mideleg_q[11];
  assign _133_ = ext_intr_i && (* src = "./riscv_csr_regfile.v:470.9-470.43" *) _141_;
  assign _134_ = timer_intr_i && (* src = "./riscv_csr_regfile.v:471.9-471.42" *) csr_mideleg_q[7];
  assign _135_ = timer_intr_i && (* src = "./riscv_csr_regfile.v:472.9-472.42" *) _142_;
  assign _136_ = 32'd1 && (* src = "./riscv_csr_regfile.v:475.9-475.59" *) _117_;
  assign _137_ = _124_ && (* src = "./riscv_csr_regfile.v:597.14-597.58" *) _126_;
  assign _138_ = _128_ || (* src = "./riscv_csr_regfile.v:167.10-167.88" *) _127_;
  assign _139_ = _109_ || (* src = "./riscv_csr_regfile.v:169.10-169.58" *) _110_;
  assign _140_ = _139_ || (* src = "./riscv_csr_regfile.v:169.10-169.76" *) _333_;
  assign _141_ = ~ (* src = "./riscv_csr_regfile.v:470.25-470.43" *) csr_mideleg_q[11];
  assign _142_ = ~ (* src = "./riscv_csr_regfile.v:472.25-472.42" *) csr_mideleg_q[7];
  assign _143_ = _129_ | (* src = "./riscv_csr_regfile.v:172.21-172.98" *) _130_;
  assign buffer_mip_w = _143_ | (* src = "./riscv_csr_regfile.v:172.21-172.114" *) csr_mip_upd_q;
  assign _144_ = { csr_sr_q[31:19], 1'h0, csr_sr_q[17:9], 1'h0, csr_sr_q[7:6], 2'h0, csr_sr_q[3:2], 2'h0 } | (* src = "./riscv_csr_regfile.v:459.36-459.201" *) { 13'h0000, csr_wdata_i[18], 9'h000, csr_wdata_i[8], 2'h0, csr_wdata_i[5:4], 2'h0, csr_wdata_i[1:0] };
  assign _145_ = { csr_mip_q[31:10], 1'h0, csr_mip_q[8:6], 1'h0, csr_mip_q[4:2], 1'h0, csr_mip_q[0] } | (* src = "./riscv_csr_regfile.v:460.40-460.138" *) { 22'h000000, csr_wdata_i[9], 3'h0, csr_wdata_i[5], 3'h0, csr_wdata_i[1], 1'h0 };
  assign _146_ = { csr_mie_q[31:10], 1'h0, csr_mie_q[8:6], 1'h0, csr_mie_q[4:2], 1'h0, csr_mie_q[0] } | (* src = "./riscv_csr_regfile.v:461.40-461.138" *) { 22'h000000, csr_wdata_i[9], 3'h0, csr_wdata_i[5], 3'h0, csr_wdata_i[1], 1'h0 };
  assign _014_ = _038_ | (* src = "./riscv_csr_regfile.v:484.17-484.43" *) { csr_mip_next_q[31:12], _012_[11], csr_mip_next_q[10], _012_[9], csr_mip_next_q[8], _012_[7], csr_mip_next_q[6], _012_[5], csr_mip_next_q[4:0] };
  (* src = "./riscv_csr_regfile.v:585.1-630.4" *)
  always @(posedge clk_i)
    branch_r <= _000_;
  (* src = "./riscv_csr_regfile.v:585.1-630.4" *)
  always @(posedge clk_i)
    branch_target_r <= _001_;
  (* src = "./riscv_csr_regfile.v:497.1-577.4" *)
  always @(posedge clk_i)
    csr_mepc_q <= _007_;
  (* src = "./riscv_csr_regfile.v:497.1-577.4" *)
  always @(posedge clk_i)
    csr_mcause_q <= _002_;
  (* src = "./riscv_csr_regfile.v:497.1-577.4" *)
  always @(posedge clk_i)
    csr_sr_q <= _026_;
  (* src = "./riscv_csr_regfile.v:497.1-577.4" *)
  always @(posedge clk_i)
    csr_mtvec_q <= _024_;
  (* src = "./riscv_csr_regfile.v:497.1-577.4" *)
  always @(posedge clk_i)
    csr_mip_q <= _013_;
  (* src = "./riscv_csr_regfile.v:497.1-577.4" *)
  always @(posedge clk_i)
    csr_mie_q <= _009_;
  (* src = "./riscv_csr_regfile.v:497.1-577.4" *)
  always @(posedge clk_i)
    csr_mpriv_q <= 2'h3;
  (* src = "./riscv_csr_regfile.v:497.1-577.4" *)
  always @(posedge clk_i)
    csr_mcycle_q <= _005_;
  (* src = "./riscv_csr_regfile.v:497.1-577.4" *)
  always @(posedge clk_i)
    csr_mcycle_h_q <= _004_;
  (* src = "./riscv_csr_regfile.v:497.1-577.4" *)
  always @(posedge clk_i)
    csr_mscratch_q <= _016_;
  (* src = "./riscv_csr_regfile.v:497.1-577.4" *)
  always @(posedge clk_i)
    csr_mtval_q <= _022_;
  (* src = "./riscv_csr_regfile.v:497.1-577.4" *)
  always @(posedge clk_i)
    csr_mtimecmp_q <= _020_;
  (* src = "./riscv_csr_regfile.v:497.1-577.4" *)
  always @(posedge clk_i)
    csr_mtime_ie_q <= _018_;
  (* src = "./riscv_csr_regfile.v:497.1-577.4" *)
  always @(posedge clk_i)
    csr_mideleg_q <= 32'd0;
  (* src = "./riscv_csr_regfile.v:497.1-577.4" *)
  always @(posedge clk_i)
    csr_sepc_q <= 32'd0;
  (* src = "./riscv_csr_regfile.v:497.1-577.4" *)
  always @(posedge clk_i)
    csr_stvec_q <= 32'd0;
  (* src = "./riscv_csr_regfile.v:497.1-577.4" *)
  always @(posedge clk_i)
    csr_satp_q <= 32'd0;
  (* src = "./riscv_csr_regfile.v:497.1-577.4" *)
  always @(posedge clk_i)
    csr_mip_next_q <= _011_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  always @(posedge clk_i)
    csr_mepc_r <= _008_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  always @(posedge clk_i)
    csr_mcause_r <= _003_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  always @(posedge clk_i)
    csr_mtval_r <= _023_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  always @(posedge clk_i)
    csr_sr_r <= _027_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  always @(posedge clk_i)
    csr_mtvec_r <= _025_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  always @(posedge clk_i)
    csr_mip_r <= _014_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  always @(posedge clk_i)
    csr_mie_r <= _010_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  always @(posedge clk_i)
    csr_mcycle_r <= _006_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  always @(posedge clk_i)
    csr_mscratch_r <= _017_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  always @(posedge clk_i)
    csr_mtimecmp_r <= _021_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  always @(posedge clk_i)
    csr_mtime_ie_r <= _019_;
  (* src = "./riscv_csr_regfile.v:253.1-485.4" *)
  always @(posedge clk_i)
    csr_mip_next_r <= { csr_mip_next_q[31:12], _012_[11], csr_mip_next_q[10], _012_[9], csr_mip_next_q[8], _012_[7], csr_mip_next_q[6], _012_[5], csr_mip_next_q[4:0] };
  (* src = "./riscv_csr_regfile.v:178.1-213.4" *)
  always @(posedge clk_i)
    rdata_r <= _031_;
  (* src = "./riscv_csr_regfile.v:164.1-170.27" *)
  always @(posedge clk_i)
    csr_mip_upd_q <= _015_;
  (* src = "./riscv_csr_regfile.v:153.1-157.30" *)
  always @(posedge clk_i)
    irq_priv_q <= _030_;
  (* src = "./riscv_csr_regfile.v:132.1-150.4" *)
  always @(posedge clk_i)
    irq_masked_r <= _028_;
  (* src = "./riscv_csr_regfile.v:132.1-150.4" *)
  always @(posedge clk_i)
    irq_priv_r <= 2'h3;
  assign _147_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 32'hxxxxxxxx : _332_;
  assign _069_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 32'hxxxxxxxx : _147_;
  assign _148_ = is_exception_w ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:399.14-399.28|./riscv_csr_regfile.v:399.10-465.8" *) csr_mip_q : _083_;
  assign _151_ = is_exception_w ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:619.14-619.28|./riscv_csr_regfile.v:619.10-629.8" *) 32'hxxxxxxxx : _331_;
  assign _149_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 32'hxxxxxxxx : _148_;
  assign _071_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 32'hxxxxxxxx : _149_;
  assign _150_ = is_exception_w ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:399.14-399.28|./riscv_csr_regfile.v:399.10-465.8" *) csr_mtvec_q : _088_;
  assign _152_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 32'hxxxxxxxx : _150_;
  assign _076_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 32'hxxxxxxxx : _152_;
  function [31:0] _429_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:415.9-427.16" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _429_ = b[31:0];
      2'b1?:
        _429_ = b[63:32];
      default:
        _429_ = a;
    endcase
  endfunction
  assign _153_ = _429_(32'd0, { exception_pc_i, exception_addr_i }, { _157_, _155_ });
  assign _155_ = | (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:415.9-427.16" *) _154_;
  assign _154_[0] = exception_i == (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:415.9-427.16" *) 6'h12;
  assign _154_[1] = exception_i == (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:415.9-427.16" *) 6'h14;
  assign _154_[2] = exception_i == (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:415.9-427.16" *) 6'h15;
  assign _154_[3] = exception_i == (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:415.9-427.16" *) 6'h16;
  assign _154_[4] = exception_i == (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:415.9-427.16" *) 6'h17;
  assign _154_[5] = exception_i == (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:415.9-427.16" *) 6'h1d;
  assign _154_[6] = exception_i == (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:415.9-427.16" *) 6'h1f;
  assign _157_ = | (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:415.9-427.16" *) _156_;
  assign _156_[0] = exception_i == (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:415.9-427.16" *) 6'h10;
  assign _156_[1] = exception_i == (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:415.9-427.16" *) 6'h11;
  assign _156_[2] = exception_i == (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:415.9-427.16" *) 6'h1c;
  assign _158_ = is_exception_w ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:399.14-399.28|./riscv_csr_regfile.v:399.10-465.8" *) _153_ : 32'hxxxxxxxx;
  assign _159_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 32'hxxxxxxxx : _158_;
  assign _094_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 32'hxxxxxxxx : _159_;
  assign _160_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 23'hxxxxxx : _036_[31:9];
  assign _035_[31:9] = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 23'hxxxxxx : _160_;
  assign _161_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 2'hx : _036_[7:6];
  assign _035_[7:6] = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 2'hx : _161_;
  assign _162_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 3'hx : _036_[4:2];
  assign _164_ = _137_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:597.14-597.58|./riscv_csr_regfile.v:597.10-629.8" *) 32'hxxxxxxxx : _151_;
  assign _035_[4:2] = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 3'hx : _162_;
  assign _163_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 1'hx : _036_[0];
  assign _035_[0] = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 1'hx : _163_;
  assign _091_ = _119_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:591.9-591.29|./riscv_csr_regfile.v:591.5-629.8" *) 32'hxxxxxxxx : _164_;
  assign _165_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 1'hx : _036_[1];
  assign _035_[1] = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 1'hx : _165_;
  assign _168_ = _122_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:625.14-625.34|./riscv_csr_regfile.v:625.10-629.8" *) 1'h1 : 1'h0;
  assign _166_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 1'hx : _036_[8];
  assign _035_[8] = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 1'hx : _166_;
  assign _167_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 1'hx : _036_[5];
  assign _035_[5] = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 1'hx : _167_;
  assign _169_ = is_exception_w ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:619.14-619.28|./riscv_csr_regfile.v:619.10-629.8" *) 1'hx : _168_;
  assign _170_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 1'hx : _073_;
  assign _060_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 1'hx : _170_;
  assign _171_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 32'hxxxxxxxx : _074_;
  assign _061_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 32'hxxxxxxxx : _171_;
  assign _172_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 32'hxxxxxxxx : _072_;
  assign _059_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 32'hxxxxxxxx : _172_;
  assign _175_ = _137_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:597.14-597.58|./riscv_csr_regfile.v:597.10-629.8" *) 1'hx : _169_;
  assign _173_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 32'hxxxxxxxx : _069_;
  assign _056_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 32'hxxxxxxxx : _173_;
  assign _174_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 32'hxxxxxxxx : _071_;
  assign _058_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 32'hxxxxxxxx : _174_;
  assign _176_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 32'hxxxxxxxx : _076_;
  assign _063_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 32'hxxxxxxxx : _176_;
  assign _090_ = _119_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:591.9-591.29|./riscv_csr_regfile.v:591.5-629.8" *) 1'hx : _175_;
  assign _177_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 32'hxxxxxxxx : _087_;
  assign _075_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 32'hxxxxxxxx : _177_;
  assign _178_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 32'hxxxxxxxx : _100_;
  assign _096_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 32'hxxxxxxxx : _178_;
  assign _179_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 32'hxxxxxxxx : _081_;
  assign _181_ = is_exception_w ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:619.14-619.28|./riscv_csr_regfile.v:619.10-629.8" *) csr_mtvec_q : _091_;
  assign _068_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 32'hxxxxxxxx : _179_;
  assign _180_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) csr_sr_q[31:13] : _035_[31:13];
  assign _099_[31:13] = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 19'hxxxxx : _180_;
  assign _182_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) csr_sr_q[10:9] : _035_[10:9];
  assign _099_[10:9] = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 2'hx : _182_;
  assign _183_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) csr_sr_q[6] : _035_[6];
  assign _099_[6] = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 1'hx : _183_;
  assign _184_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) csr_sr_q[4] : _035_[4];
  assign _099_[4] = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 1'hx : _184_;
  assign _185_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) csr_sr_q[2] : _035_[2];
  assign _099_[2] = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 1'hx : _185_;
  assign _186_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) csr_sr_q[0] : _035_[0];
  assign _099_[0] = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 1'hx : _186_;
  assign _187_ = _116_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:338.13-338.37|./riscv_csr_regfile.v:338.9-362.12" *) 1'h1 : csr_sr_q[7];
  assign _188_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) _187_ : 1'hx;
  assign _033_[0] = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 1'hx : _188_;
  assign _189_ = _116_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:338.13-338.37|./riscv_csr_regfile.v:338.9-362.12" *) csr_sr_q[7] : csr_sr_q[3];
  assign _190_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) _189_ : 1'hx;
  assign _104_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 1'hx : _190_;
  assign _192_ = _137_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:597.14-597.58|./riscv_csr_regfile.v:597.10-629.8" *) 32'hxxxxxxxx : _181_;
  assign _191_ = _116_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:338.13-338.37|./riscv_csr_regfile.v:338.9-362.12" *) csr_sr_q[8] : 1'h0;
  assign _193_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) _191_ : 1'hx;
  assign _033_[1] = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 1'hx : _193_;
  assign _194_ = _116_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:338.13-338.37|./riscv_csr_regfile.v:338.9-362.12" *) csr_sr_q[5] : 1'h1;
  assign _195_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) _194_ : 1'hx;
  assign _032_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 1'hx : _195_;
  assign _196_ = _116_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:338.13-338.37|./riscv_csr_regfile.v:338.9-362.12" *) csr_sr_q[1] : csr_sr_q[5];
  assign _197_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) _196_ : 1'hx;
  assign _079_ = _119_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:591.9-591.29|./riscv_csr_regfile.v:591.5-629.8" *) 32'hxxxxxxxx : _192_;
  assign _102_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 1'hx : _197_;
  assign _198_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) _034_ : _035_[12:11];
  assign _099_[12:11] = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 2'hx : _198_;
  assign _199_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) _033_ : _035_[8:7];
  assign _099_[8:7] = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 2'hx : _199_;
  assign _200_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) _032_ : _035_[5];
  assign _099_[5] = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 1'hx : _200_;
  assign _201_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) _104_ : _035_[3];
  assign _203_ = is_exception_w ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:619.14-619.28|./riscv_csr_regfile.v:619.10-629.8" *) 1'h1 : _090_;
  assign _099_[3] = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 1'hx : _201_;
  assign _202_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) _102_ : _035_[1];
  assign _099_[1] = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 1'hx : _202_;
  assign _204_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) csr_mtime_ie_q : _060_;
  assign _206_ = _137_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:597.14-597.58|./riscv_csr_regfile.v:597.10-629.8" *) 1'hx : _203_;
  assign _047_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 1'hx : _204_;
  assign _205_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) csr_mtimecmp_q : _061_;
  assign _048_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 32'hxxxxxxxx : _205_;
  assign _207_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) csr_mscratch_q : _059_;
  assign _046_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 32'hxxxxxxxx : _207_;
  assign _208_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) csr_mie_q : _056_;
  assign _044_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 32'hxxxxxxxx : _208_;
  assign _209_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) csr_mip_q : _058_;
  assign _045_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 32'hxxxxxxxx : _209_;
  assign _210_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) csr_mtvec_q : _063_;
  assign _078_ = _119_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:591.9-591.29|./riscv_csr_regfile.v:591.5-629.8" *) 1'hx : _206_;
  assign _050_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 32'hxxxxxxxx : _210_;
  assign _211_ = _116_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:338.13-338.37|./riscv_csr_regfile.v:338.9-362.12" *) 2'h0 : csr_sr_q[12:11];
  assign _212_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) _211_ : 2'hx;
  assign _034_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 2'hx : _212_;
  assign _213_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) csr_mtval_q : _075_;
  assign _062_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 32'hxxxxxxxx : _213_;
  assign _214_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) csr_mcause_q : _096_;
  assign _092_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 32'hxxxxxxxx : _214_;
  assign _215_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) csr_mepc_q : _068_;
  assign _055_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 32'hxxxxxxxx : _215_;
  assign _027_[31:13] = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) csr_sr_q[31:13] : _099_[31:13];
  assign _027_[10:9] = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) csr_sr_q[10:9] : _099_[10:9];
  assign _027_[6] = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) csr_sr_q[6] : _099_[6];
  assign _027_[4] = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) csr_sr_q[4] : _099_[4];
  assign _027_[2] = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) csr_sr_q[2] : _099_[2];
  assign _027_[0] = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) csr_sr_q[0] : _099_[0];
  assign _216_ = _137_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:597.14-597.58|./riscv_csr_regfile.v:597.10-629.8" *) 32'hxxxxxxxx : _079_;
  assign _217_ = irq_masked_r[11] ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:305.22-305.37|./riscv_csr_regfile.v:305.18-306.51" *) 32'd2147483659 : csr_mcause_q;
  assign _218_ = irq_masked_r[7] ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:303.22-303.36|./riscv_csr_regfile.v:303.18-306.51" *) 32'hxxxxxxxx : _217_;
  assign _219_ = irq_masked_r[3] ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:301.17-301.31|./riscv_csr_regfile.v:301.13-306.51" *) 32'hxxxxxxxx : _218_;
  assign _220_ = _114_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:284.13-284.31|./riscv_csr_regfile.v:284.9-332.12" *) _219_ : 32'hxxxxxxxx;
  assign _080_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) _220_ : 32'hxxxxxxxx;
  assign _221_ = irq_masked_r[7] ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:303.22-303.36|./riscv_csr_regfile.v:303.18-306.51" *) 32'd2147483655 : _080_;
  assign _066_ = _119_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:591.9-591.29|./riscv_csr_regfile.v:591.5-629.8" *) 32'hxxxxxxxx : _216_;
  assign _222_ = irq_masked_r[3] ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:301.17-301.31|./riscv_csr_regfile.v:301.13-306.51" *) 32'hxxxxxxxx : _221_;
  assign _223_ = _114_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:284.13-284.31|./riscv_csr_regfile.v:284.9-332.12" *) _222_ : 32'hxxxxxxxx;
  assign _067_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) _223_ : 32'hxxxxxxxx;
  assign _224_ = irq_masked_r[3] ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:301.17-301.31|./riscv_csr_regfile.v:301.13-306.51" *) 32'd2147483651 : _067_;
  assign _225_ = _114_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:284.13-284.31|./riscv_csr_regfile.v:284.9-332.12" *) _224_ : 32'hxxxxxxxx;
  assign _054_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) _225_ : 32'hxxxxxxxx;
  assign _226_ = _114_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:284.13-284.31|./riscv_csr_regfile.v:284.9-332.12" *) _054_ : csr_mcause_q;
  assign _042_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) _226_ : 32'hxxxxxxxx;
  assign _227_ = _114_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:284.13-284.31|./riscv_csr_regfile.v:284.9-332.12" *) 32'd0 : csr_mtval_q;
  assign _049_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) _227_ : 32'hxxxxxxxx;
  assign _228_ = _114_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:284.13-284.31|./riscv_csr_regfile.v:284.9-332.12" *) exception_pc_i : csr_mepc_q;
  assign _043_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) _228_ : 32'hxxxxxxxx;
  assign _229_ = _114_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:284.13-284.31|./riscv_csr_regfile.v:284.9-332.12" *) 1'h0 : csr_sr_q[3];
  assign _064_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) _229_ : 1'hx;
  assign _230_ = _114_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:284.13-284.31|./riscv_csr_regfile.v:284.9-332.12" *) csr_mpriv_q : csr_sr_q[12:11];
  assign _095_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) _230_ : 2'hx;
  assign _231_ = _114_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:284.13-284.31|./riscv_csr_regfile.v:284.9-332.12" *) csr_sr_q[3] : csr_sr_q[7];
  assign _089_[0] = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) _231_ : 1'hx;
  assign _232_ = _137_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:597.14-597.58|./riscv_csr_regfile.v:597.10-629.8" *) 1'hx : _078_;
  assign _233_ = _114_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:284.13-284.31|./riscv_csr_regfile.v:284.9-332.12" *) csr_sr_q[8] : _115_;
  assign _089_[1] = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) _233_ : 1'hx;
  assign _234_ = _114_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:284.13-284.31|./riscv_csr_regfile.v:284.9-332.12" *) csr_sr_q[5] : csr_sr_q[1];
  assign _077_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) _234_ : 1'hx;
  assign _235_ = _114_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:284.13-284.31|./riscv_csr_regfile.v:284.9-332.12" *) csr_sr_q[1] : 1'h0;
  assign _065_ = _119_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:591.9-591.29|./riscv_csr_regfile.v:591.5-629.8" *) 1'hx : _232_;
  assign _051_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) _235_ : 1'hx;
  assign _027_[12:11] = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) _095_ : _099_[12:11];
  assign _027_[8:7] = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) _089_ : _099_[8:7];
  assign _027_[5] = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) _077_ : _099_[5];
  assign _027_[3] = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) _064_ : _099_[3];
  assign _027_[1] = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) _051_ : _099_[1];
  assign _023_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) _049_ : _062_;
  assign _003_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) _042_ : _092_;
  assign _008_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) _043_ : _055_;
  assign _236_ = _121_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:600.13-600.37|./riscv_csr_regfile.v:600.9-610.12" *) csr_mepc_q : csr_sepc_q;
  assign _039_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) csr_mtime_ie_q : _047_;
  assign _021_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) csr_mtimecmp_q : _048_;
  assign _237_ = _137_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:597.14-597.58|./riscv_csr_regfile.v:597.10-629.8" *) _236_ : 32'hxxxxxxxx;
  assign _017_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) csr_mscratch_q : _046_;
  assign _010_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) csr_mie_q : _044_;
  assign _038_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) csr_mip_q : _045_;
  assign _025_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) csr_mtvec_q : _050_;
  assign _053_ = _119_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:591.9-591.29|./riscv_csr_regfile.v:591.5-629.8" *) 32'hxxxxxxxx : _237_;
  function [31:0] _604_;
    input [31:0] a;
    input [415:0] b;
    input [12:0] s;
    (* full_case = 32'd1 *)
    (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:182.5-212.12" *)
    (* parallel_case *)
    casez (s)
      13'b????????????1:
        _604_ = b[31:0];
      13'b???????????1?:
        _604_ = b[63:32];
      13'b??????????1??:
        _604_ = b[95:64];
      13'b?????????1???:
        _604_ = b[127:96];
      13'b????????1????:
        _604_ = b[159:128];
      13'b???????1?????:
        _604_ = b[191:160];
      13'b??????1??????:
        _604_ = b[223:192];
      13'b?????1???????:
        _604_ = b[255:224];
      13'b????1????????:
        _604_ = b[287:256];
      13'b???1?????????:
        _604_ = b[319:288];
      13'b??1??????????:
        _604_ = b[351:320];
      13'b?1???????????:
        _604_ = b[383:352];
      13'b1????????????:
        _604_ = b[415:384];
      default:
        _604_ = a;
    endcase
  endfunction
  assign _031_ = _604_(32'd0, { csr_mscratch_q, csr_mepc_q, csr_mtvec_q, csr_mcause_q[31], 27'h0000000, csr_mcause_q[3:0], csr_mtval_q, csr_sr_q, 20'h00000, csr_mip_q[11], 1'h0, csr_mip_q[9], 1'h0, csr_mip_q[7], 1'h0, csr_mip_q[5], 1'h0, csr_mip_q[3], 1'h0, csr_mip_q[1], 21'h000000, csr_mie_q[11], 1'h0, csr_mie_q[9], 1'h0, csr_mie_q[7], 1'h0, csr_mie_q[5], 1'h0, csr_mie_q[3], 1'h0, csr_mie_q[1], 1'h0, csr_mcycle_q, csr_mcycle_h_q, cpu_id_i, misa_i, csr_mtimecmp_q }, { _251_, _250_, _249_, _248_, _247_, _246_, _245_, _244_, _243_, _241_, _240_, _239_, _238_ });
  assign _238_ = csr_raddr_i == (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:182.5-212.12" *) 12'h7c0;
  assign _239_ = csr_raddr_i == (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:182.5-212.12" *) 12'h301;
  assign _240_ = csr_raddr_i == (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:182.5-212.12" *) 12'hf14;
  assign _241_ = csr_raddr_i == (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:182.5-212.12" *) 12'hc81;
  assign _243_ = | (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:182.5-212.12" *) _242_;
  assign _242_[0] = csr_raddr_i == (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:182.5-212.12" *) 12'hc00;
  assign _242_[1] = csr_raddr_i == (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:182.5-212.12" *) 12'hc01;
  assign _244_ = csr_raddr_i == (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:182.5-212.12" *) 12'h304;
  assign _245_ = csr_raddr_i == (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:182.5-212.12" *) 12'h344;
  assign _246_ = csr_raddr_i == (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:182.5-212.12" *) 12'h300;
  assign _247_ = csr_raddr_i == (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:182.5-212.12" *) 12'h343;
  assign _248_ = csr_raddr_i == (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:182.5-212.12" *) 12'h342;
  assign _249_ = csr_raddr_i == (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:182.5-212.12" *) 12'h305;
  assign _250_ = csr_raddr_i == (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:182.5-212.12" *) 12'h341;
  assign _251_ = csr_raddr_i == (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:182.5-212.12" *) 12'h340;
  assign _252_ = _140_ ? (* src = "./riscv_csr_regfile.v:169.10-169.76|./riscv_csr_regfile.v:169.6-170.27" *) 1'h0 : csr_mip_upd_q;
  assign _253_ = _138_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:167.10-167.88|./riscv_csr_regfile.v:167.6-170.27" *) 1'h1 : _252_;
  assign _015_ = rst_i ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:165.5-165.10|./riscv_csr_regfile.v:165.1-170.27" *) 1'h0 : _253_;
  assign _254_ = _255_ ? (* src = "./riscv_csr_regfile.v:156.10-156.23|./riscv_csr_regfile.v:156.6-157.30" *) irq_priv_r : irq_priv_q;
  assign _030_ = rst_i ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:154.5-154.10|./riscv_csr_regfile.v:154.1-157.30" *) 2'h3 : _254_;
  assign _256_ = _137_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:597.14-597.58|./riscv_csr_regfile.v:597.10-629.8" *) 1'h1 : 1'hx;
  assign _052_ = _119_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:591.9-591.29|./riscv_csr_regfile.v:591.5-629.8" *) 1'hx : _256_;
  assign _257_ = _137_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:597.14-597.58|./riscv_csr_regfile.v:597.10-629.8" *) _053_ : _066_;
  assign _041_ = _119_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:591.9-591.29|./riscv_csr_regfile.v:591.5-629.8" *) 32'hxxxxxxxx : _257_;
  assign _258_ = _137_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:597.14-597.58|./riscv_csr_regfile.v:597.10-629.8" *) _052_ : _065_;
  assign _040_ = _119_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:591.9-591.29|./riscv_csr_regfile.v:591.5-629.8" *) 1'hx : _258_;
  assign _001_ = _119_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:591.9-591.29|./riscv_csr_regfile.v:591.5-629.8" *) _335_ : _041_;
  assign _000_ = _119_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:591.9-591.29|./riscv_csr_regfile.v:591.5-629.8" *) 1'h1 : _040_;
  assign _011_ = rst_i ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:498.5-498.10|./riscv_csr_regfile.v:498.1-577.4" *) 32'd0 : _334_;
  assign _018_ = rst_i ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:498.5-498.10|./riscv_csr_regfile.v:498.1-577.4" *) 1'h0 : csr_mtime_ie_r;
  assign _020_ = rst_i ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:498.5-498.10|./riscv_csr_regfile.v:498.1-577.4" *) 32'd0 : csr_mtimecmp_r;
  assign _016_ = rst_i ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:498.5-498.10|./riscv_csr_regfile.v:498.1-577.4" *) 32'd0 : csr_mscratch_r;
  assign _005_ = rst_i ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:498.5-498.10|./riscv_csr_regfile.v:498.1-577.4" *) 32'd0 : csr_mcycle_r;
  assign _009_ = rst_i ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:498.5-498.10|./riscv_csr_regfile.v:498.1-577.4" *) 32'd0 : csr_mie_r;
  assign _013_ = rst_i ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:498.5-498.10|./riscv_csr_regfile.v:498.1-577.4" *) 32'd0 : csr_mip_r;
  assign _024_ = rst_i ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:498.5-498.10|./riscv_csr_regfile.v:498.1-577.4" *) 32'd0 : csr_mtvec_r;
  assign _022_ = rst_i ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:498.5-498.10|./riscv_csr_regfile.v:498.1-577.4" *) 32'd0 : csr_mtval_r;
  assign _002_ = rst_i ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:498.5-498.10|./riscv_csr_regfile.v:498.1-577.4" *) 32'd0 : csr_mcause_r;
  assign _026_ = rst_i ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:498.5-498.10|./riscv_csr_regfile.v:498.1-577.4" *) 32'd0 : csr_sr_r;
  assign _007_ = rst_i ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:498.5-498.10|./riscv_csr_regfile.v:498.1-577.4" *) 32'd0 : csr_mepc_r;
  assign _259_ = _118_ ? (* src = "./riscv_csr_regfile.v:556.9-556.37|./riscv_csr_regfile.v:556.5-557.50" *) _105_ : csr_mcycle_h_q;
  assign _004_ = rst_i ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:498.5-498.10|./riscv_csr_regfile.v:498.1-577.4" *) 32'd0 : _259_;
  assign _260_ = csr_mideleg_q[7] ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:477.13-477.29|./riscv_csr_regfile.v:477.9-480.48" *) csr_mtime_ie_q : _057_;
  assign _097_ = _136_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:475.9-475.59|./riscv_csr_regfile.v:475.5-482.8" *) _260_ : 1'hx;
  assign _261_ = csr_mideleg_q[7] ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:477.13-477.29|./riscv_csr_regfile.v:477.9-480.48" *) _070_ : csr_mtime_ie_q;
  assign _101_ = _136_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:475.9-475.59|./riscv_csr_regfile.v:475.5-482.8" *) _261_ : 1'hx;
  assign _019_ = _136_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:475.9-475.59|./riscv_csr_regfile.v:475.5-482.8" *) 1'h0 : _039_;
  assign _012_[7] = _136_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:475.9-475.59|./riscv_csr_regfile.v:475.5-482.8" *) _101_ : _070_;
  assign _012_[5] = _136_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:475.9-475.59|./riscv_csr_regfile.v:475.5-482.8" *) _097_ : _057_;
  assign _070_ = _135_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:472.9-472.42|./riscv_csr_regfile.v:472.5-472.69" *) 1'h1 : csr_mip_next_q[7];
  assign _057_ = _134_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:471.9-471.42|./riscv_csr_regfile.v:471.5-471.69" *) 1'h1 : csr_mip_next_q[5];
  assign _012_[11] = _133_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:470.9-470.43|./riscv_csr_regfile.v:470.5-470.71" *) 1'h1 : csr_mip_next_q[11];
  assign _012_[9] = _132_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:469.9-469.43|./riscv_csr_regfile.v:469.5-469.70" *) 1'h1 : csr_mip_next_q[9];
  assign _262_ = _263_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:434.9-464.16" *) csr_wdata_i : csr_mscratch_q;
  assign _263_ = csr_waddr_i == (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:434.9-464.16" *) 12'h340;
  assign _264_ = is_exception_w ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:399.14-399.28|./riscv_csr_regfile.v:399.10-465.8" *) 32'hxxxxxxxx : _262_;
  assign _265_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 32'hxxxxxxxx : _264_;
  assign _084_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 32'hxxxxxxxx : _265_;
  assign _266_ = _267_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:434.9-464.16" *) 1'h1 : csr_mtime_ie_q;
  assign _267_ = csr_waddr_i == (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:434.9-464.16" *) 12'h7c0;
  assign _268_ = is_exception_w ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:399.14-399.28|./riscv_csr_regfile.v:399.10-465.8" *) 1'hx : _266_;
  assign _269_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 1'hx : _268_;
  assign _085_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 1'hx : _269_;
  assign _270_ = _271_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:434.9-464.16" *) csr_wdata_i : csr_mtimecmp_q;
  assign _271_ = csr_waddr_i == (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:434.9-464.16" *) 12'h7c0;
  assign _272_ = is_exception_w ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:399.14-399.28|./riscv_csr_regfile.v:399.10-465.8" *) 32'hxxxxxxxx : _270_;
  assign _273_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 32'hxxxxxxxx : _272_;
  assign _086_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 32'hxxxxxxxx : _273_;
  function [31:0] _673_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:434.9-464.16" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _673_ = b[31:0];
      2'b1?:
        _673_ = b[63:32];
      default:
        _673_ = a;
    endcase
  endfunction
  assign _274_ = _673_(csr_mie_q, { 20'h00000, csr_wdata_i[11], 1'h0, csr_wdata_i[9], 1'h0, csr_wdata_i[7], 1'h0, csr_wdata_i[5], 1'h0, csr_wdata_i[3], 1'h0, csr_wdata_i[1], 1'h0, _146_ }, { _276_, _275_ });
  assign _275_ = csr_waddr_i == (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:434.9-464.16" *) 12'h104;
  assign _276_ = csr_waddr_i == (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:434.9-464.16" *) 12'h304;
  assign _277_ = is_exception_w ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:399.14-399.28|./riscv_csr_regfile.v:399.10-465.8" *) 32'hxxxxxxxx : _274_;
  assign _278_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 32'hxxxxxxxx : _277_;
  assign _082_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 32'hxxxxxxxx : _278_;
  function [31:0] _679_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:434.9-464.16" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _679_ = b[31:0];
      2'b1?:
        _679_ = b[63:32];
      default:
        _679_ = a;
    endcase
  endfunction
  assign _279_ = _679_(csr_mip_q, { 20'h00000, csr_wdata_i[11], 1'h0, csr_wdata_i[9], 1'h0, csr_wdata_i[7], 1'h0, csr_wdata_i[5], 1'h0, csr_wdata_i[3], 1'h0, csr_wdata_i[1], 1'h0, _145_ }, { _281_, _280_ });
  assign _280_ = csr_waddr_i == (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:434.9-464.16" *) 12'h144;
  assign _281_ = csr_waddr_i == (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:434.9-464.16" *) 12'h344;
  assign _282_ = is_exception_w ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:399.14-399.28|./riscv_csr_regfile.v:399.10-465.8" *) 32'hxxxxxxxx : _279_;
  assign _283_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 32'hxxxxxxxx : _282_;
  assign _083_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 32'hxxxxxxxx : _283_;
  assign _284_ = _285_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:434.9-464.16" *) csr_wdata_i : csr_mtvec_q;
  assign _285_ = csr_waddr_i == (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:434.9-464.16" *) 12'h305;
  assign _286_ = is_exception_w ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:399.14-399.28|./riscv_csr_regfile.v:399.10-465.8" *) 32'hxxxxxxxx : _284_;
  assign _287_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 32'hxxxxxxxx : _286_;
  assign _088_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 32'hxxxxxxxx : _287_;
  function [31:0] _690_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:434.9-464.16" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _690_ = b[31:0];
      2'b1?:
        _690_ = b[63:32];
      default:
        _690_ = a;
    endcase
  endfunction
  assign _288_ = _690_(csr_sr_q, { csr_wdata_i, _144_ }, { _290_, _289_ });
  assign _289_ = csr_waddr_i == (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:434.9-464.16" *) 12'h100;
  assign _290_ = csr_waddr_i == (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:434.9-464.16" *) 12'h300;
  assign _291_ = is_exception_w ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:399.14-399.28|./riscv_csr_regfile.v:399.10-465.8" *) 32'hxxxxxxxx : _288_;
  assign _292_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 32'hxxxxxxxx : _291_;
  assign _037_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 32'hxxxxxxxx : _292_;
  assign _293_ = _294_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:434.9-464.16" *) csr_wdata_i : csr_mtval_q;
  assign _294_ = csr_waddr_i == (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:434.9-464.16" *) 12'h343;
  assign _295_ = is_exception_w ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:399.14-399.28|./riscv_csr_regfile.v:399.10-465.8" *) 32'hxxxxxxxx : _293_;
  assign _296_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 32'hxxxxxxxx : _295_;
  assign _098_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 32'hxxxxxxxx : _296_;
  assign _297_ = _298_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:434.9-464.16" *) { csr_wdata_i[31], 27'h0000000, csr_wdata_i[3:0] } : csr_mcause_q;
  assign _298_ = csr_waddr_i == (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:434.9-464.16" *) 12'h342;
  assign _299_ = is_exception_w ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:399.14-399.28|./riscv_csr_regfile.v:399.10-465.8" *) 32'hxxxxxxxx : _297_;
  assign _300_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 32'hxxxxxxxx : _299_;
  assign _103_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 32'hxxxxxxxx : _300_;
  assign _301_ = _302_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:434.9-464.16" *) csr_wdata_i : csr_mepc_q;
  assign _302_ = csr_waddr_i == (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:0.0-0.0|./riscv_csr_regfile.v:434.9-464.16" *) 12'h341;
  assign _303_ = is_exception_w ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:399.14-399.28|./riscv_csr_regfile.v:399.10-465.8" *) 32'hxxxxxxxx : _301_;
  assign _304_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 32'hxxxxxxxx : _303_;
  assign _093_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 32'hxxxxxxxx : _304_;
  assign _305_ = is_exception_w ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:399.14-399.28|./riscv_csr_regfile.v:399.10-465.8" *) csr_sr_q[31:13] : _037_[31:13];
  assign _306_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 19'hxxxxx : _305_;
  assign _036_[31:13] = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 19'hxxxxx : _306_;
  assign _307_ = is_exception_w ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:399.14-399.28|./riscv_csr_regfile.v:399.10-465.8" *) csr_sr_q[10:8] : _037_[10:8];
  assign _308_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 3'hx : _307_;
  assign _036_[10:8] = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 3'hx : _308_;
  assign _309_ = is_exception_w ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:399.14-399.28|./riscv_csr_regfile.v:399.10-465.8" *) csr_sr_q[6:4] : _037_[6:4];
  assign _310_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 3'hx : _309_;
  assign _036_[6:4] = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 3'hx : _310_;
  assign _311_ = is_exception_w ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:399.14-399.28|./riscv_csr_regfile.v:399.10-465.8" *) csr_sr_q[2:0] : _037_[2:0];
  assign _312_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 3'hx : _311_;
  assign _036_[2:0] = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 3'hx : _312_;
  assign _313_ = is_exception_w ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:399.14-399.28|./riscv_csr_regfile.v:399.10-465.8" *) { 28'h0000000, exception_i[3:0] } : _103_;
  assign _314_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 32'hxxxxxxxx : _313_;
  assign _100_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 32'hxxxxxxxx : _314_;
  assign _315_ = is_exception_w ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:399.14-399.28|./riscv_csr_regfile.v:399.10-465.8" *) _094_ : _098_;
  assign _316_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 32'hxxxxxxxx : _315_;
  assign _087_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 32'hxxxxxxxx : _316_;
  assign _317_ = is_exception_w ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:399.14-399.28|./riscv_csr_regfile.v:399.10-465.8" *) exception_pc_i : _093_;
  assign _318_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 32'hxxxxxxxx : _317_;
  assign _081_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 32'hxxxxxxxx : _318_;
  assign _319_ = is_exception_w ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:399.14-399.28|./riscv_csr_regfile.v:399.10-465.8" *) 1'h0 : _037_[3];
  assign _320_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 1'hx : _319_;
  assign _036_[3] = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 1'hx : _320_;
  assign _321_ = is_exception_w ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:399.14-399.28|./riscv_csr_regfile.v:399.10-465.8" *) csr_mpriv_q : _037_[12:11];
  assign _322_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 2'hx : _321_;
  assign _036_[12:11] = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 2'hx : _322_;
  assign _323_ = is_exception_w ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:399.14-399.28|./riscv_csr_regfile.v:399.10-465.8" *) csr_sr_q[3] : _037_[7];
  assign _324_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 1'hx : _323_;
  assign _036_[7] = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 1'hx : _324_;
  assign _325_ = is_exception_w ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:399.14-399.28|./riscv_csr_regfile.v:399.10-465.8" *) csr_mtime_ie_q : _085_;
  assign _326_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 1'hx : _325_;
  assign _073_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 1'hx : _326_;
  assign _327_ = is_exception_w ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:399.14-399.28|./riscv_csr_regfile.v:399.10-465.8" *) csr_mtimecmp_q : _086_;
  assign _328_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 32'hxxxxxxxx : _327_;
  assign _074_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 32'hxxxxxxxx : _328_;
  assign _331_ = _122_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:625.14-625.34|./riscv_csr_regfile.v:625.10-629.8" *) _106_ : 32'd0;
  assign _329_ = is_exception_w ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:399.14-399.28|./riscv_csr_regfile.v:399.10-465.8" *) csr_mscratch_q : _084_;
  assign _330_ = _131_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:335.14-335.58|./riscv_csr_regfile.v:335.10-465.8" *) 32'hxxxxxxxx : _329_;
  assign _072_ = _113_ ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:281.9-281.39|./riscv_csr_regfile.v:281.5-465.8" *) 32'hxxxxxxxx : _330_;
  assign _332_ = is_exception_w ? (* full_case = 32'd1 *) (* src = "./riscv_csr_regfile.v:399.14-399.28|./riscv_csr_regfile.v:399.10-465.8" *) csr_mie_q : _082_;
  assign _255_ = | (* src = "./riscv_csr_regfile.v:156.10-156.23" *) irq_masked_r;
  assign _333_ = | (* src = "./riscv_csr_regfile.v:169.63-169.75" *) exception_i;
  assign _028_ = csr_sr_q[3] ? (* src = "./riscv_csr_regfile.v:147.27-147.62" *) _029_ : 32'd0;
  assign _334_ = buffer_mip_w ? (* src = "./riscv_csr_regfile.v:553.27-553.64" *) csr_mip_next_r : 32'd0;
  assign _335_ = _120_ ? (* src = "./riscv_csr_regfile.v:594.27-594.75" *) csr_mtvec_q : csr_stvec_q;
  assign { _012_[31:12], _012_[10], _012_[8], _012_[6], _012_[4:0] } = { csr_mip_next_q[31:12], csr_mip_next_q[10], csr_mip_next_q[8], csr_mip_next_q[6], csr_mip_next_q[4:0] };
  assign csr_branch_o = branch_r;
  assign csr_rdata_o = rdata_r;
  assign csr_target_o = branch_target_r;
  assign exception_s_w = 1'h0;
  assign interrupt_o = irq_masked_r;
  assign priv_o = csr_mpriv_q;
  assign satp_o = csr_satp_q;
  assign status_o = csr_sr_q;
endmodule
