/* Generated by Yosys 0.43+3 (git sha1 b08688f71, clang++ 14.0.0-1ubuntu1.1 -fPIC -Os) */
module comparator(p, a, b, clk);
  wire _0_;
  wire _1_;
  input [7:0] a;
  wire [7:0] a;
  input [7:0] b;
  wire [7:0] b;
  input clk;
  wire clk;
  output p;
  reg p;
  assign _1_ = a <  b;
  always @(posedge clk)
    p <= _0_;
  assign _0_ = _1_ ?  1'h0 : 1'h1;
endmodule
