/* Generated by Yosys 0.43+3 (git sha1 b08688f71, clang++ 14.0.0-1ubuntu1.1 -fPIC -Os) */
module large_system(clk, rst_n, a, b, start, add_en, mul_en, result, count, done);
  wire [15:0] _00_;
  wire [7:0] _01_;
  wire _02_;
  wire _03_;
  wire [7:0] _04_;
  wire [15:0] _05_;
  wire [15:0] _06_;
  wire [1:0] _07_;
  wire [1:0] _08_;
  wire [1:0] _09_;
  wire [1:0] _10_;
  wire [31:0] _11_;
  wire [15:0] _12_;
  wire [15:0] _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire [15:0] _18_;
  wire _19_;
  wire _20_;
  wire [15:0] _21_;
  wire [15:0] _22_;
  wire [1:0] _23_;
  wire _24_;
  wire [1:0] _25_;
  wire _26_;
  wire [1:0] _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  input [7:0] a;
  wire [7:0] a;
  input add_en;
  wire add_en;
  reg [15:0] add_result;
  input [7:0] b;
  wire [7:0] b;
  input clk;
  wire clk;
  output [7:0] count;
  reg [7:0] count;
  output done;
  reg done;
  reg done_reg;
  reg [7:0] internal_count;
  input mul_en;
  wire mul_en;
  reg [15:0] mul_result;
  wire [1:0] next_state;
  output [15:0] result;
  reg [15:0] result;
  input rst_n;
  wire rst_n;
  input start;
  wire start;
  reg [1:0] state;
  assign _11_ = internal_count +  32'd1;
  assign _12_ = a +  b;
  assign _13_ = a *  b;
  always @(posedge clk)
    count <= _01_;
  always @(posedge clk)
    done <= _02_;
  always @(posedge clk)
    result <= _06_;
  always @(posedge clk)
    done_reg <= _03_;
  always @(posedge clk)
    mul_result <= _05_;
  always @(posedge clk)
    add_result <= _00_;
  always @(posedge clk)
    state <= _07_;
  always @(posedge clk)
    internal_count <= _04_;
  assign _01_ = rst_n ?  internal_count : 8'h00;
  assign _02_ = rst_n ?  done_reg : 1'h0;
  function [0:0] _46_;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    casez (s)
      3'b??1:
        _46_ = b[0:0];
      3'b?1?:
        _46_ = b[1:1];
      3'b1??:
        _46_ = b[2:2];
      default:
        _46_ = a;
    endcase
  endfunction
  assign _14_ = _46_(1'h0, { done_reg, done_reg, 1'h1 }, { _17_, _16_, _15_ });
  assign _15_ = state ==  2'h3;
  assign _16_ = state ==  2'h2;
  assign _17_ = state ==  2'h1;
  assign _03_ = rst_n ?  _14_ : 1'h0;
  function [15:0] _51_;
    input [15:0] a;
    input [31:0] b;
    input [1:0] s;
    casez (s)
      2'b?1:
        _51_ = b[15:0];
      2'b1?:
        _51_ = b[31:16];
      default:
        _51_ = a;
    endcase
  endfunction
  assign _18_ = _51_(result, { add_result, mul_result }, { _20_, _19_ });
  assign _19_ = state ==  2'h2;
  assign _20_ = state ==  2'h1;
  assign _06_ = rst_n ?  _18_ : 16'h0000;
  assign _21_ = mul_en ?  _13_ : mul_result;
  assign _05_ = rst_n ?  _21_ : 16'h0000;
  assign _22_ = add_en ?  _12_ : add_result;
  assign _00_ = rst_n ?  _22_ : 16'h0000;
  assign _23_ = mul_en ?  2'h3 : 2'h2;
  assign _10_ = _24_ ?  _23_ : 2'hx;
  assign _24_ = state ==  2'h2;
  assign _25_ = add_en ?  2'h2 : 2'h1;
  assign _09_ = _26_ ?  _25_ : 2'hx;
  assign _26_ = state ==  2'h1;
  assign _27_ = start ?  2'h1 : 2'h0;
  assign _08_ = _28_ ?  _27_ : 2'hx;
  assign _28_ = !  state;
  function [1:0] _68_;
    input [1:0] a;
    input [7:0] b;
    input [3:0] s;
    casez (s)
      4'b???1:
        _68_ = b[1:0];
      4'b??1?:
        _68_ = b[3:2];
      4'b?1??:
        _68_ = b[5:4];
      4'b1???:
        _68_ = b[7:6];
      default:
        _68_ = a;
    endcase
  endfunction
  assign next_state = _68_(2'hx, { _08_, _09_, _10_, 2'h0 }, { _32_, _31_, _30_, _29_ });
  assign _29_ = state ==  2'h3;
  assign _30_ = state ==  2'h2;
  assign _31_ = state ==  2'h1;
  assign _32_ = !  state;
  assign _07_ = rst_n ?  next_state : 2'h0;
  assign _04_ = rst_n ?  _11_[7:0] : 8'h00;
endmodule
