/* Generated by Yosys 0.43+3 (git sha1 b08688f71, clang++ 14.0.0-1ubuntu1.1 -fPIC -Os) */
module control_example(a, b, clk, RESET, result);
  wire [7:0] _00_;
  wire _01_;
  wire _02_;
  wire [7:0] _03_;
  wire [7:0] _04_;
  wire [7:0] _05_;
  wire [7:0] _06_;
  input RESET;
  wire RESET;
  input [7:0] a;
  wire [7:0] a;
  input [7:0] b;
  wire [7:0] b;
  input clk;
  wire clk;
  output [7:0] result;
  reg [7:0] result;
  assign _01_ = a >  b;
  assign _02_ = a <  b;
  always @(posedge clk)
    result <= _00_;
  assign _03_ = _02_ ?  _06_ : 8'hff;
  assign _04_ = _01_ ?  _05_ : _03_;
  assign _00_ = RESET ?  8'h00 : _04_;
  assign _05_ = a -  b;
  assign _06_ = b -  a;
endmodule
