/* Generated by Yosys 0.43+3 (git sha1 b08688f71, clang++ 14.0.0-1ubuntu1.1 -fPIC -Os) */
module soc_design_JTAG_sim_scfifo_r(clk, fifo_rd, rst_n, fifo_EF, fifo_rdata, rfifo_full, rfifo_used);
  wire [31:0] _00_;
  wire _01_;
  wire [31:0] _02_;
  wire [31:0] _03_;
  wire [31:0] _04_;
  reg [31:0] bytes_left;
  input clk;
  wire clk;
  output fifo_EF;
  wire fifo_EF;
  input fifo_rd;
  wire fifo_rd;
  reg fifo_rd_d;
  output [7:0] fifo_rdata;
  wire [7:0] fifo_rdata;
  wire new_rom;
  wire [31:0] num_bytes;
  wire [6:0] rfifo_entries;
  output rfifo_full;
  wire rfifo_full;
  output [5:0] rfifo_used;
  wire [5:0] rfifo_used;
  input rst_n;
  wire rst_n;
  assign fifo_EF = !  bytes_left;
  assign rfifo_full = bytes_left >  7'h40;
  always @(posedge clk)
    bytes_left <= _00_;
  always @(posedge clk)
    fifo_rd_d <= _01_;
  assign _02_ = fifo_rd_d ?  _03_ : bytes_left;
  assign _00_ = rst_n ?  _02_ : 32'd0;
  assign _01_ = rst_n ?  fifo_rd : 1'h0;
  assign _03_ = bytes_left -  1'h1;
  assign { _04_[31:7], rfifo_entries[6], rfifo_used } = rfifo_full ?  32'd64 : bytes_left;
  assign _04_[6:0] = { rfifo_entries[6], rfifo_used };
  assign fifo_rdata = 8'h00;
  assign new_rom = 1'h0;
  assign num_bytes = 32'd0;
  assign rfifo_entries[5:0] = rfifo_used;
endmodule
