/* Generated by Yosys 0.43+3 (git sha1 b08688f71, clang++ 14.0.0-1ubuntu1.1 -fPIC -Os) */
module simple_if_example(data_in, data_out);
  input [3:0] data_in;
  wire [3:0] data_in;
  output data_out;
  wire data_out;
  wire msb;
  assign data_out = data_in[3] ?  1'h1 : 1'h0;
  assign msb = data_in[3];
endmodule
