/* Generated by Yosys 0.43+3 (git sha1 b08688f71, clang++ 14.0.0-1ubuntu1.1 -fPIC -Os) */
module three_state_fsm(clk, rst, in, state);
  wire [1:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire [1:0] _04_;
  wire [1:0] _05_;
  wire [1:0] _06_;
  wire [1:0] _07_;
  wire [1:0] _08_;
  wire [1:0] _09_;
  input clk;
  wire clk;
  input in;
  wire in;
  input rst;
  wire rst;
  output [1:0] state;
  reg [1:0] state;
  assign _01_ = !  state;
  assign _02_ = state ==  2'h1;
  assign _03_ = state ==  2'h2;
  always @(posedge clk)
    state <= _00_;
  assign _04_ = in ?  2'h2 : state;
  assign _05_ = _02_ ?  _04_ : _09_;
  assign _06_ = in ?  2'h1 : state;
  assign _07_ = _01_ ?  _06_ : _05_;
  assign _00_ = rst ?  2'h0 : _07_;
  assign _08_ = in ?  2'h0 : state;
  assign _09_ = _03_ ?  _08_ : 2'h0;
endmodule
