# rm -rf ./data
# rm -rf ./ast_like_data/
# rm -rf test_ast.v
ifdivide=$1
filename=$2

# Define log file path.
LOG_DIR=../log
LOG_FILE=$LOG_DIR/log.txt

# Ensure log directory exists.
mkdir -p $LOG_DIR

# # Use basename to extract the file name without extension.
name_without_extension=$(basename "$filename" .v)

filename_s="${name_without_extension}.s"
# .s file generated by parser.
new_filename_v="${name_without_extension}_ast_clean.v"
new_filename_s="${name_without_extension}_ast_clean.s"
new_filename_j="${name_without_extension}_ast_clean.json"
# Generated AST files.

# # yiliu_ removable
timeout 120s ~/py/CDFG/Stagira/stagira.exe -toegg ../yosys_data/$filename > ./origin_s_data/$filename_s
if [ $? -ne 0 ]; then
    echo "$filename : Parser failed" >> $LOG_FILE
    exit 1
fi

# python3 tree.py -i ./origin_s_data $filename_s -o ./data -r -j -e

# #yiliu

timeout 120s python3 ./src/auto_yosys.py $filename
if [ $? -ne 0 ]; then
    echo "$filename : Yosys failed" >> $LOG_FILE
    exit 1
fi
# Parser generates .s file.
# Set file variables for directory changes.
timeout 120s ../Stagira/stagira.exe -toegg ./tmp/yosys_output_data_clean/$new_filename_v > ./tmp/s_exp/$new_filename_s
if [ $? -ne 0 ]; then
    echo "$filename : Parser failed" >> $LOG_FILE
    exit 1
fi
# Convert .s to .json via tree.py.
timeout 120s python3 ./src/tree.py -i ./tmp/s_exp $new_filename_s -r -j -p -o ./tmp/ast
if [ $? -ne 0 ]; then
    echo "$filename : Ast failed" >> $LOG_FILE
    exit 1
fi

if [ "$ifdivide" = "-divide" ]; then
    timeout 120s python3 ./src/auto_run.py -d $new_filename_j > output.log 2>&1
else
    timeout 120s python3 ./src/auto_run.py $new_filename_j > output.log 2>&1
fi
if [ $? -ne 0 ]; then
    # Check for AssertionError.
    if grep -q "AssertionError" output.log; then
        # Write error details to fail.log.
        grep "AssertionError" output.log | sed "s|^|$filename: |">> $LOG_FILE
        echo "AssertionError detected. See fail.log for details."
        exit 1
    else
        echo "$filename : cdfg generation failed" >> $LOG_FILE
        exit 1
    fi
fi
