/* Generated by Yosys 0.43+3 (git sha1 b08688f71, clang++ 14.0.0-1ubuntu1.1 -fPIC -Os) */
module led_chaser(clk, rst, led);
  wire [7:0] _0_;
  input clk;
  wire clk;
  output [7:0] led;
  reg [7:0] led;
  input rst;
  wire rst;
  always @(posedge clk)
    led <= _0_;
  assign _0_ = rst ?  8'h01 : { led[6:0], led[7] };
endmodule
