/* Generated by Yosys 0.43+3 (git sha1 b08688f71, clang++ 14.0.0-1ubuntu1.1 -fPIC -Os) */

(* src = "./test.v:1.1-49.10" *)
module soc_design_JTAG_sim_scfifo_r(clk, fifo_rd, rst_n, fifo_EF, fifo_rdata, rfifo_full, rfifo_used);
  (* src = "./test.v:26.1-41.4" *)
  wire [31:0] _00_;
  (* src = "./test.v:26.1-41.4" *)
  wire _01_;
  wire [31:0] _02_;
  (* src = "./test.v:37.25-37.42" *)
  wire [31:0] _03_;
  (* src = "./test.v:44.24-44.57" *)
  (* unused_bits = "6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _04_;
  (* src = "./test.v:17.18-17.28" *)
  reg [31:0] bytes_left;
  (* src = "./test.v:14.18-14.21" *)
  input clk;
  wire clk;
  (* src = "./test.v:10.18-10.25" *)
  output fifo_EF;
  wire fifo_EF;
  (* src = "./test.v:15.18-15.25" *)
  input fifo_rd;
  wire fifo_rd;
  (* src = "./test.v:19.18-19.27" *)
  reg fifo_rd_d;
  (* src = "./test.v:11.18-11.28" *)
  output [7:0] fifo_rdata;
  wire [7:0] fifo_rdata;
  (* src = "./test.v:21.18-21.25" *)
  wire new_rom;
  (* src = "./test.v:22.18-22.27" *)
  wire [31:0] num_bytes;
  (* src = "./test.v:23.18-23.31" *)
  (* unused_bits = "6" *)
  wire [6:0] rfifo_entries;
  (* src = "./test.v:12.18-12.28" *)
  output rfifo_full;
  wire rfifo_full;
  (* src = "./test.v:13.18-13.28" *)
  output [5:0] rfifo_used;
  wire [5:0] rfifo_used;
  (* src = "./test.v:16.18-16.23" *)
  input rst_n;
  wire rst_n;
  assign fifo_EF = ! (* src = "./test.v:42.18-42.37" *) bytes_left;
  assign rfifo_full = bytes_left > (* src = "./test.v:43.21-43.39" *) 7'h40;
  (* src = "./test.v:26.1-41.4" *)
  always @(posedge clk)
    bytes_left <= _00_;
  (* src = "./test.v:26.1-41.4" *)
  always @(posedge clk)
    fifo_rd_d <= _01_;
  assign _02_ = fifo_rd_d ? (* src = "./test.v:36.11-36.20|./test.v:36.7-37.43" *) _03_ : bytes_left;
  assign _00_ = rst_n ? (* full_case = 32'd1 *) (* src = "./test.v:28.7-28.17|./test.v:28.3-40.8" *) _02_ : 32'd0;
  assign _01_ = rst_n ? (* full_case = 32'd1 *) (* src = "./test.v:28.7-28.17|./test.v:28.3-40.8" *) fifo_rd : 1'h0;
  assign _03_ = bytes_left - (* src = "./test.v:37.25-37.42" *) 1'h1;
  assign { _04_[31:7], rfifo_entries[6], rfifo_used } = rfifo_full ? (* src = "./test.v:44.24-44.57" *) 32'd64 : bytes_left;
  assign _04_[6:0] = { rfifo_entries[6], rfifo_used };
  assign fifo_rdata = 8'h00;
  assign new_rom = 1'h0;
  assign num_bytes = 32'd0;
  assign rfifo_entries[5:0] = rfifo_used;
endmodule
