/* Generated by Yosys 0.43+3 (git sha1 b08688f71, clang++ 14.0.0-1ubuntu1.1 -fPIC -Os) */
module dataflow_optimization(a, b, c, d, result);
  input [31:0] a;
  wire [31:0] a;
  input [31:0] b;
  wire [31:0] b;
  input [31:0] c;
  wire [31:0] c;
  input [31:0] d;
  wire [31:0] d;
  output [31:0] result;
  wire [31:0] result;
  wire [31:0] t1;
  wire [31:0] t2;
  wire [31:0] t3;
  wire [31:0] t4;
  assign t1 = a +  b;
  assign t2 = a +  b;
  assign t3 = t1 +  c;
  assign t4 = t2 +  1'h1;
  assign result = t3 +  t4;
endmodule
